// Canonical ccxpLite values. Preserve public CSS names when extending the system.
export const tokens = {
  colorPrimary: "#9F5FA5",
  colorAccent: "#d5dbe1",
  colorBrand: "#9F5FA5",
  colorLegacyBlueText: "#2e4978",
  colorLegacyRedText: "#b85c68",
  colorBg: "#ffffff",
  colorSurface: "#ffffff",
  colorSidebarSurface: "#f5f7f9",
  colorSurfaceMuted: "#f5f7f9",
  colorBorder: "rgba(31, 41, 51, 0.12)",
  colorSidebarDivider: "rgba(31, 41, 51, 0.16)",
  colorSidebarSearchSurface: "rgba(255, 255, 255, 0.9)",
  colorSidebarSearchGradientStart: "rgba(255, 255, 255, 0.98)",
  colorSidebarSearchBorder: "rgba(31, 41, 51, 0.1)",
  colorPrimaryFocusBorder: "rgba(159, 95, 165, 0.28)",
  colorPrimaryFocusRing: "rgba(159, 95, 165, 0.08)",
  colorPrimaryHoverSurface: "rgba(159, 95, 165, 0.06)",
  colorPrimaryHoverSolid: "#8E4E94",
  colorPrimaryMutedSurface: "rgba(159, 95, 165, 0.04)",
  colorPrimaryGlow: "rgba(159, 95, 165, 0.18)",
  colorLabActiveSurface: "rgba(159, 95, 165, 0.14)",
  colorLabActiveBorder: "rgba(159, 95, 165, 0.24)",
  colorLabActiveText: "#9F5FA5",
  colorLabInactiveSurface: "rgba(82, 96, 109, 0.1)",
  colorLabInactiveBorder: "rgba(82, 96, 109, 0.18)",
  colorLabInactiveText: "#425466",
  colorLabSwitchShadow: "rgba(17, 24, 39, 0.12)",
  colorSidebarSearchPlaceholder: "#6b7280",
  colorText: "#111827",
  colorTextMuted: "#52606d",
  colorTransparent: "transparent",
  colorSkeletonSurfaceEndTint: "#eef2f6",
  colorSkeletonHighlightStart: "rgba(255, 255, 255, 0)",
  colorSkeletonHighlightSoft: "rgba(255, 255, 255, 0.3)",
  colorSkeletonHighlightStrong: "rgba(255, 255, 255, 0.88)",
  spacingXs: "6px",
  spacingSm: "10px",
  spacingMd: "16px",
  spacingLg: "24px",
  spacingXl: "32px",
  spacing2xs: "4px",
  spacing3xs: "2px",
  spacingInlineSm: "8px",
  spacingInsetSm: "12px",
  spacingInsetMd: "14px",
  spacingInsetLg: "18px",
  spacingBrandInline: "12px",
  spacingSidebarSearchInset: "12px",
  spacingSidebarExperimentInsetX: "12px",
  spacingSidebarExperimentInsetY: "8px",
  sidebarRowPaddingY: "12px",
  sidebarRowPaddingX: "10px",
  sidebarRowGap: "6px",
  sidebarTreeIndentStep: "1em",
  radiusSm: "10px",
  radiusMd: "14px",
  radiusLg: "20px",
  radiusXs: "6px",
  radiusInput: "8px",
  radiusBrand: "12px",
  radiusFull: "999px",
  fontSans: '"Noto Sans TC", "PingFang TC", "Microsoft JhengHei", sans-serif',
  fontBrand: '"Futura", "Futura PT", "Avenir Next", sans-serif',
  fontWeightRegular: "400",
  fontWeightStrong: "700",
  fontWeightHeavy: "800",
  fontVariantNumericTabular: "tabular-nums",
  fontSizeCaption: "14px",
  fontSizeNav: "14px",
  fontSizeUtility: "14px",
  fontSizeBody: "16px",
  fontSizeSidebarBrand: "20px",
  sizeSidebarBrandLogo: "30px",
  sizeSidebarCategoryLeading: "1.5em",
  sizeSidebarControl: "24px",
  sizeSidebarGuideLine: "2px",
  sizeSidebarSearchSpacer: "14px",
  sizeSidebarSearchWidth: "268px",
  spacingSidebarBrandWordGap: "0.5ch",
  sizeSidebarHeaderDividerWidth: "100%",
  sizeSidebarHeaderDividerHeight: "1px",
  sizeSidebarSearchIcon: "20px",
  sizeSidebarExperimentSwitch: "124px",
  sizeSidebarExperimentSwitchExpanded: "168px",
  sizeLandingBrandLogo: "32px",
  sizeLandingHeaderHeight: "68px",
  sizeFormControlWidth: "320px",
  sizeLoginControlHeight: "48px",
  sizePasswordToggleOffset: "44px",
  sizeIconButtonSm: "24px",
  sizeIconButtonMd: "36px",
  sizeSidebarSectionIcon: "42px",
  sizeSidebarCategoryCardIcon: "48px",
  sizeControlMinWidth: "112px",
  sizeControlHeightSm: "38px",
  sizeControlHeightMd: "44px",
  sizeSidebarSectionCardMinHeight: "72px",
  sizeSidebarCategoryCardMinHeight: "72px",
  sizeSidebarDestinationFrameOffset: "276px",
  sizeAnnouncementDivider: "18px",
  fontSizePageTitle: "26px",
  fontSizeDisplay: "30px",
  fontSizeSectionTitle: "18px",
  fontSizeChip: "13px",
  landingMaxWidth: "960px",
  sidebarWidth: "324px",
} as const;

export const cssVariables = {
  "--ccxp-lite-primary": tokens.colorPrimary,
  "--ccxp-lite-accent": tokens.colorAccent,
  "--ccxp-lite-brand": tokens.colorBrand,
  "--ccxp-lite-brand-logo-filter":
    "brightness(0) saturate(100%) invert(19%) sepia(49%) saturate(2697%) hue-rotate(278deg) brightness(89%) contrast(92%)",
  "--ccxp-lite-legacy-blue-text": tokens.colorLegacyBlueText,
  "--ccxp-lite-legacy-red-text": tokens.colorLegacyRedText,
  "--ccxp-lite-bg": tokens.colorBg,
  "--ccxp-lite-surface": tokens.colorSurface,
  "--ccxp-lite-sidebar-surface": tokens.colorSidebarSurface,
  "--ccxp-lite-surface-muted": tokens.colorSurfaceMuted,
  "--ccxp-lite-border": tokens.colorBorder,
  "--ccxp-lite-sidebar-divider-color": tokens.colorSidebarDivider,
  "--ccxp-lite-sidebar-search-surface": tokens.colorSidebarSearchSurface,
  "--ccxp-lite-sidebar-search-gradient-start": tokens.colorSidebarSearchGradientStart,
  "--ccxp-lite-sidebar-search-border": tokens.colorSidebarSearchBorder,
  "--ccxp-lite-primary-focus-border": tokens.colorPrimaryFocusBorder,
  "--ccxp-lite-primary-focus-ring": tokens.colorPrimaryFocusRing,
  "--ccxp-lite-primary-hover-surface": tokens.colorPrimaryHoverSurface,
  "--ccxp-lite-primary-hover-solid": tokens.colorPrimaryHoverSolid,
  "--ccxp-lite-primary-muted-surface": tokens.colorPrimaryMutedSurface,
  "--ccxp-lite-primary-glow": tokens.colorPrimaryGlow,
  "--ccxp-lite-lab-active-surface": tokens.colorLabActiveSurface,
  "--ccxp-lite-lab-active-border": tokens.colorLabActiveBorder,
  "--ccxp-lite-lab-active-text": tokens.colorLabActiveText,
  "--ccxp-lite-lab-inactive-surface": tokens.colorLabInactiveSurface,
  "--ccxp-lite-lab-inactive-border": tokens.colorLabInactiveBorder,
  "--ccxp-lite-lab-inactive-text": tokens.colorLabInactiveText,
  "--ccxp-lite-lab-switch-shadow": tokens.colorLabSwitchShadow,
  "--ccxp-lite-sidebar-search-placeholder": tokens.colorSidebarSearchPlaceholder,
  "--ccxp-lite-text": tokens.colorText,
  "--ccxp-lite-text-muted": tokens.colorTextMuted,
  "--ccxp-lite-transparent": tokens.colorTransparent,
  "--ccxp-lite-skeleton-surface-end-tint": tokens.colorSkeletonSurfaceEndTint,
  "--ccxp-lite-skeleton-highlight-start": tokens.colorSkeletonHighlightStart,
  "--ccxp-lite-skeleton-highlight-soft": tokens.colorSkeletonHighlightSoft,
  "--ccxp-lite-skeleton-highlight-strong": tokens.colorSkeletonHighlightStrong,
  "--ccxp-lite-skeleton-surface-start":
    "color-mix(in srgb, var(--ccxp-lite-surface) 60%, var(--ccxp-lite-accent))",
  "--ccxp-lite-skeleton-surface-end":
    "color-mix(in srgb, var(--ccxp-lite-surface) 86%, var(--ccxp-lite-skeleton-surface-end-tint))",
  "--ccxp-lite-tabs-active-surface":
    "color-mix(in srgb, var(--ccxp-lite-surface) 72%, var(--ccxp-lite-accent))",
  "--ccxp-lite-tabs-focus-outline":
    "color-mix(in srgb, var(--ccxp-lite-primary) 45%, var(--ccxp-lite-bg))",
  "--ccxp-lite-danger-flash-transparent":
    "color-mix(in srgb, var(--ccxp-lite-type-danger-color) 0%, var(--ccxp-lite-transparent))",
  "--ccxp-lite-danger-flash-outline":
    "color-mix(in srgb, var(--ccxp-lite-type-danger-color) 78%, var(--ccxp-lite-bg))",
  "--ccxp-lite-danger-flash-shadow":
    "color-mix(in srgb, var(--ccxp-lite-type-danger-color) 14%, var(--ccxp-lite-transparent))",
  "--ccxp-lite-spacing-xs": tokens.spacingXs,
  "--ccxp-lite-spacing-sm": tokens.spacingSm,
  "--ccxp-lite-spacing-md": tokens.spacingMd,
  "--ccxp-lite-spacing-lg": tokens.spacingLg,
  "--ccxp-lite-spacing-xl": tokens.spacingXl,
  "--ccxp-lite-spacing-2xs": tokens.spacing2xs,
  "--ccxp-lite-spacing-3xs": tokens.spacing3xs,
  "--ccxp-lite-spacing-inline-sm": tokens.spacingInlineSm,
  "--ccxp-lite-spacing-inset-sm": tokens.spacingInsetSm,
  "--ccxp-lite-spacing-inset-md": tokens.spacingInsetMd,
  "--ccxp-lite-spacing-inset-lg": tokens.spacingInsetLg,
  "--ccxp-lite-spacing-brand-inline": tokens.spacingBrandInline,
  "--ccxp-lite-spacing-sidebar-search-inset": tokens.spacingSidebarSearchInset,
  "--ccxp-lite-spacing-sidebar-experiment-inset-x": tokens.spacingSidebarExperimentInsetX,
  "--ccxp-lite-spacing-sidebar-experiment-inset-y": tokens.spacingSidebarExperimentInsetY,
  "--ccxp-lite-sidebar-row-padding-y": tokens.sidebarRowPaddingY,
  "--ccxp-lite-sidebar-row-padding-x": tokens.sidebarRowPaddingX,
  "--ccxp-lite-sidebar-row-gap": tokens.sidebarRowGap,
  "--ccxp-lite-sidebar-tree-indent-step": tokens.sidebarTreeIndentStep,
  "--ccxp-lite-radius-xs": tokens.radiusXs,
  "--ccxp-lite-radius-sm": tokens.radiusSm,
  "--ccxp-lite-radius-input": tokens.radiusInput,
  "--ccxp-lite-radius-md": tokens.radiusMd,
  "--ccxp-lite-radius-lg": tokens.radiusLg,
  "--ccxp-lite-radius-brand": tokens.radiusBrand,
  "--ccxp-lite-radius-full": tokens.radiusFull,
  "--ccxp-lite-font-sans": tokens.fontSans,
  "--ccxp-lite-font-brand": tokens.fontBrand,
  "--ccxp-lite-font-weight-regular": tokens.fontWeightRegular,
  "--ccxp-lite-font-weight-strong": tokens.fontWeightStrong,
  "--ccxp-lite-font-weight-heavy": tokens.fontWeightHeavy,
  "--ccxp-lite-font-variant-numeric-tabular": tokens.fontVariantNumericTabular,
  "--ccxp-lite-font-size-caption": tokens.fontSizeCaption,
  "--ccxp-lite-font-size-nav": tokens.fontSizeNav,
  "--ccxp-lite-font-size-utility": tokens.fontSizeUtility,
  "--ccxp-lite-font-size-body": tokens.fontSizeBody,
  "--ccxp-lite-font-size-sidebar-brand": tokens.fontSizeSidebarBrand,
  "--ccxp-lite-size-sidebar-brand-logo": tokens.sizeSidebarBrandLogo,
  "--ccxp-lite-size-sidebar-category-leading": tokens.sizeSidebarCategoryLeading,
  "--ccxp-lite-size-sidebar-control": tokens.sizeSidebarControl,
  "--ccxp-lite-size-sidebar-guide-line": tokens.sizeSidebarGuideLine,
  "--ccxp-lite-size-sidebar-search-spacer": tokens.sizeSidebarSearchSpacer,
  "--ccxp-lite-size-sidebar-search-width": tokens.sizeSidebarSearchWidth,
  "--ccxp-lite-spacing-sidebar-brand-word-gap": tokens.spacingSidebarBrandWordGap,
  "--ccxp-lite-size-sidebar-header-divider-width": tokens.sizeSidebarHeaderDividerWidth,
  "--ccxp-lite-size-sidebar-header-divider-height": tokens.sizeSidebarHeaderDividerHeight,
  "--ccxp-lite-size-sidebar-search-icon": tokens.sizeSidebarSearchIcon,
  "--ccxp-lite-size-sidebar-experiment-switch": tokens.sizeSidebarExperimentSwitch,
  "--ccxp-lite-size-sidebar-experiment-switch-expanded": tokens.sizeSidebarExperimentSwitchExpanded,
  "--ccxp-lite-size-landing-brand-logo": tokens.sizeLandingBrandLogo,
  "--ccxp-lite-size-landing-header-height": tokens.sizeLandingHeaderHeight,
  "--ccxp-lite-size-form-control-width": tokens.sizeFormControlWidth,
  "--ccxp-lite-size-login-control-height": tokens.sizeLoginControlHeight,
  "--ccxp-lite-size-password-toggle-offset": tokens.sizePasswordToggleOffset,
  "--ccxp-lite-size-icon-button-sm": tokens.sizeIconButtonSm,
  "--ccxp-lite-size-icon-button-md": tokens.sizeIconButtonMd,
  "--ccxp-lite-size-sidebar-section-icon": tokens.sizeSidebarSectionIcon,
  "--ccxp-lite-size-sidebar-category-card-icon": tokens.sizeSidebarCategoryCardIcon,
  "--ccxp-lite-size-control-min-width": tokens.sizeControlMinWidth,
  "--ccxp-lite-size-control-height-sm": tokens.sizeControlHeightSm,
  "--ccxp-lite-size-control-height-md": tokens.sizeControlHeightMd,
  "--ccxp-lite-size-sidebar-section-card-min-height": tokens.sizeSidebarSectionCardMinHeight,
  "--ccxp-lite-size-sidebar-category-card-min-height": tokens.sizeSidebarCategoryCardMinHeight,
  "--ccxp-lite-size-sidebar-destination-frame-offset": tokens.sizeSidebarDestinationFrameOffset,
  "--ccxp-lite-size-announcement-divider": tokens.sizeAnnouncementDivider,
  "--ccxp-lite-font-size-page-title": tokens.fontSizePageTitle,
  "--ccxp-lite-font-size-display": tokens.fontSizeDisplay,
  "--ccxp-lite-font-size-section-title": tokens.fontSizeSectionTitle,
  "--ccxp-lite-font-size-chip": tokens.fontSizeChip,
  "--ccxp-lite-sidebar-width": tokens.sidebarWidth,
  "--ccxp-lite-landing-max-width": tokens.landingMaxWidth,
  "--ccxp-lite-type-display":
    "var(--ccxp-lite-font-weight-heavy) var(--ccxp-lite-font-size-display)/1.1 var(--ccxp-lite-font-sans)",
  "--ccxp-lite-type-display-color": "var(--ccxp-lite-text)",
  "--ccxp-lite-type-page-title":
    "var(--ccxp-lite-font-weight-strong) var(--ccxp-lite-font-size-page-title)/1.2 var(--ccxp-lite-font-sans)",
  "--ccxp-lite-type-page-title-color": "var(--ccxp-lite-text)",
  "--ccxp-lite-type-primary-link": "var(--ccxp-lite-type-body-strong)",
  "--ccxp-lite-type-primary-link-color": "var(--ccxp-lite-primary)",
  "--ccxp-lite-type-info": "var(--ccxp-lite-type-body-strong)",
  "--ccxp-lite-type-info-color": "var(--ccxp-lite-legacy-blue-text)",
  "--ccxp-lite-type-danger": "var(--ccxp-lite-type-body-strong)",
  "--ccxp-lite-type-danger-color": "var(--ccxp-lite-legacy-red-text)",
  "--ccxp-lite-type-body-strong":
    "var(--ccxp-lite-font-weight-strong) var(--ccxp-lite-font-size-body)/1.55 var(--ccxp-lite-font-sans)",
  "--ccxp-lite-type-body-strong-color": "var(--ccxp-lite-text)",
  "--ccxp-lite-type-body":
    "var(--ccxp-lite-font-weight-regular) var(--ccxp-lite-font-size-body)/1.55 var(--ccxp-lite-font-sans)",
  "--ccxp-lite-type-body-color": "var(--ccxp-lite-text)",
  "--ccxp-lite-type-body-muted":
    "var(--ccxp-lite-font-weight-regular) var(--ccxp-lite-font-size-body)/1.55 var(--ccxp-lite-font-sans)",
  "--ccxp-lite-type-body-muted-color": "var(--ccxp-lite-text-muted)",
  "--ccxp-lite-type-utility":
    "var(--ccxp-lite-font-weight-strong) var(--ccxp-lite-font-size-utility)/1.4 var(--ccxp-lite-font-sans)",
  "--ccxp-lite-type-utility-color": "var(--ccxp-lite-primary)",
  "--ccxp-lite-type-nav": "var(--ccxp-lite-type-utility)",
  "--ccxp-lite-type-nav-color": "var(--ccxp-lite-primary)",
  "--ccxp-lite-type-caption": "var(--ccxp-lite-type-utility)",
  "--ccxp-lite-type-caption-color": "var(--ccxp-lite-text-muted)",
  "--ccxp-lite-type-section-label": "var(--ccxp-lite-type-utility)",
  "--ccxp-lite-type-section-label-color": "var(--ccxp-lite-primary)",
  "--ccxp-lite-dialog-width": "540px",
  "--ccxp-lite-dialog-padding": "36px",
  "--ccxp-lite-dialog-shadow": "0 20px 48px rgba(17, 24, 39, 0.2)",
  "--ccxp-lite-dialog-backdrop": "rgba(17, 24, 39, 0.36)",
  "--ccxp-lite-size-dialog-action-height": "40px",
  "--ccxp-lite-motion-fast": "120ms",
} as const;

export type TokenName = keyof typeof tokens;
export type CssTokenName = keyof typeof cssVariables;

/** Apply to the owning document's root (each CCXP frame has its own root). */
export function applyTokens(target: HTMLElement): void {
  for (const [name, value] of Object.entries(cssVariables)) {
    target.style.setProperty(name, value);
  }
}
