import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import { cssVariables } from "@ccxp-lite/tokens";

const projectRoot = fileURLToPath(new URL("../", import.meta.url));

/** Rebuild the same module sources for classic content scripts and ESM consumers. */
export async function buildDesignSystem(check = false): Promise<void> {
  const variables: Readonly<Record<string, string>> = cssVariables;
  function validateReference(name: string, ancestors: readonly string[] = []) {
    if (!(name in variables)) {
      throw new Error(`Unknown token: ${name}`);
    }
    if (ancestors.includes(name)) {
      throw new Error(`Circular token: ${[...ancestors, name].join(" -> ")}`);
    }
    for (const match of variables[name].matchAll(/var\((--[\w-]+)/g)) {
      validateReference(match[1], [...ancestors, name]);
    }
  }
  for (const name of Object.keys(variables)) {
    validateReference(name);
  }
  const cssPath = path.join(projectRoot, "packages/tokens/tokens.css");
  const css = await format(
    `/* Generated by bun run design:build. Edit packages/tokens/src/index.ts. */\n:root {\n${Object.entries(
      variables,
    )
      .map(([name, value]) => `  ${name}: ${value};`)
      .join("\n")}\n}\n`,
    { ...(await resolveConfig(cssPath)), parser: "css" },
  );
  if (check) {
    if (readFileSync(cssPath, "utf8") !== css) {
      throw new Error("Generated tokens.css is stale. Run bun run design:build and commit it.");
    }
  } else {
    writeFileSync(cssPath, css);
  }
  const outputDirectory = path.join(projectRoot, ".build/design");
  mkdirSync(outputDirectory, { recursive: true });
  await Promise.all(
    ["tokens", "ui"].map(async (name) => {
      const result = await Bun.build({
        entrypoints: [path.join(projectRoot, `scripts/design-${name}-entry.ts`)],
        target: "browser",
        format: "iife",
        minify: false,
      });
      if (!result.success) {
        throw new AggregateError(result.logs, `Could not build design ${name}`);
      }
      writeFileSync(path.join(outputDirectory, `${name}.js`), await result.outputs[0].text());
    }),
  );
}

if (import.meta.main) {
  await buildDesignSystem(process.argv.includes("--check"));
}
